### ISSUE TITLE
Could you please add cnn and conlstm?  Thanks.

### ISSUE THREAD

**Issue by miadl** [imethanlee/Traffic-Flow-Baseline#1]
Could you please add cnn and conlstm?  Thanks.

Do you have email?

**Comment by imethanlee** [comment]
Hi,

Thanks for your interests. This repo constitutes part of my FYP. However, I have recently turned to other project directions, so I will be less likely to maintain this repo (at least for the following few months). Hope you can find other related repo in Github.

Sorry for the inconvenience :(
