### ISSUE TITLE
数据集来源

### ISSUE THREAD

**Issue by bingkuaibaoer** [imethanlee/Traffic-Flow-Baseline#2]
请问您的数据集是来源于哪里呢

**Comment by imethanlee** [comment]
你好，

首先这个还是一个未经完善的repo，所以代码会存在很多问题。

关于数据集，请参考https://github.com/liyaguang/DCRNN和https://github.com/VeritasYin/STGCN_IJCAI-18。

**Comment by bingkuaibaoer** [comment]
感谢您的回答，谢谢😊
